# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ixigo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ixigo
  pod 'IQKeyboardManagerSwift'

  target 'IxigoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IxigoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
